path_classifiers:
  library:
    - "html/*"
    - "html_NG/*"
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - automake
        - autoconf
        - libtool
        - pkg-config
        - zlib1g-dev
    configure:
      command:
        - ./autogen.sh
        - ./configure
